Repository cisagov/con-pca-cicd, pull requests merged in 2020-06, with the labels that each got.

#126 Feature/cpa 207 186
  .isort.cfg
  controller/src/api/models/subscription_models.py
  controller/src/api/serializers/subscriptions_serializers.py
  controller/src/api/utils/subscription_utils.py
  controller/src/api/views/subscription_views.py
  controller/src/scripts/create_dummy_data.py
  controller/src/scripts/data/dummy_data.json
Labels: Ready for Review

#128 feature: CPA-203
  controller/src/api/serializers/reports_serializers.py
  controller/src/api/urls.py
  controller/src/api/views/report_views.py
Labels: Ready for Review

#138 feature: CPA-219
  controller/src/api/models/subscription_models.py
  controller/src/api/serializers/subscriptions_serializers.py
  controller/src/scripts/data/dummy_data.json
Labels: Ready for Review

#164 Feature/cpa 252
  controller/src/tasks/tasks.py
  controller/src/tasks/views.py
Labels: Ready for Review

#166 Feature/cpa 217
  .isort.cfg
  controller/src/api/views/subscription_views.py
  controller/src/api/views/webhook_views.py
  controller/src/config/settings.py
  controller/src/notifications/utils.py
  controller/src/notifications/views.py
  controller/src/templates/emails/mjml/subscription_started.mjml
  controller/src/templates/emails/subscription_started.html
  controller/src/templates/emails/subscription_started.txt
Labels: Ready for Review

#171 feature: CPA-272
  controller/etc/env.dist
  controller/src/config/settings.py
  controller/src/notifications/views.py
  controller/src/templates/emails/subscription_started.html
Labels: Ready for Review

#176 fix: make init
  controller/etc/env.dist
  controller/src/api/tests/serializers/subscription_serializers/test_subscription_get_serializer.py
  controller/src/api/views/subscription_views.py
  controller/src/notifications/views.py
  controller/src/reports/views.py
  controller/src/scripts/create_dummy_data.py
  controller/src/scripts/data/dummy_data.json
  controller/src/scripts/init_gophish.py
Labels: bugfix

#190 fix: docker entrypoint and static collection
  controller/docker-compose.yml
  controller/etc/Dockerfile
  controller/etc/entrypoint.sh
  controller/src/config/settings.py
  controller/src/notifications/management/commands/send_reports_emails.py
Labels: Ready for Review

#209 feature: CPA-288
  controller/README.md
  controller/docker-compose.yml
  controller/requirements.txt
Labels: Ready for Review

#218 feature: CPA-308
  controller/docker-compose.yml
  controller/src/api/models/subscription_models.py
  controller/src/api/serializers/subscriptions_serializers.py
  controller/src/api/utils/subscription_utils.py
  controller/src/api/views/subscription_views.py
  controller/src/tasks/tasks.py
  controller/src/tasks/views.py
Labels: Ready for Review

#224 feature: cpa-318
  controller/src/api/utils/subscription/subscriptions.py
  controller/src/tasks/tasks.py
  controller/src/tasks/views.py
Labels: WIP

#234 update: gophish readme
  gophish/README.md
Labels: Ready for Review

#271 fix Tag Evals
  controller/src/api/utils/generic.py
  controller/src/api/utils/template/personalize.py
  controller/src/scripts/data/tags.json
Labels: Ready for Review, bugfix

#267 feature: CPA-289
  client/AdminUI/src/app/components/user-admin/user-admin.component.html
  client/AdminUI/src/app/components/user-admin/user-admin.component.ts
  client/AdminUI/src/app/models/settings.ts
  client/AdminUI/src/assets/settings.json
  client/AdminUI/src/assets/settings.template.json
  controller/README.md
  controller/docker-compose.yml
  controller/etc/entrypoint.sh
  controller/requirements.txt
Labels: Ready for Review
